# Generated by Django 5.2.6 on 2025-09-27 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('official_quota', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['num'],
                'indexes': [models.Index(fields=['num'], name='exam_chapte_num_ffe0cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('single', 'single'), ('multi', 'multi'), ('judge', 'judge')], default='single', max_length=10)),
                ('stem', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('is_excluded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('mock', 'mock'), ('rehab', 'rehab'), ('srs', 'srs')], max_length=16)),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter'], name='exam_questi_chapter_99eb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_excluded'], name='exam_questi_is_excl_4a858b_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='exam_choice_questio_a635c3_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['is_correct'], name='exam_choice_is_corr_3a85e9_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'answered_at'], name='exam_attemp_user_id_5f0ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['question', 'answered_at'], name='exam_attemp_questio_c021a4_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['mode'], name='exam_attemp_mode_b68b73_idx'),
        ),
    ]
